# Generated by Django 3.2.13 on 2022-04-30 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['full_name'], 'verbose_name': 'paciente', 'verbose_name_plural': 'pacientes'},
        ),
    ]
