# Generated by Django 3.2.13 on 2022-04-27 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='evaluations/attachments/')),
            ],
            options={
                'verbose_name': 'evaluation attachment',
                'verbose_name_plural': 'evaluation attachments',
            },
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'verbose_name': 'prescrição', 'verbose_name_plural': 'prescrição'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'serviço', 'verbose_name_plural': 'serviços'},
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='core.service', verbose_name='serviço'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescription_date',
            field=models.DateField(verbose_name='data da prescrição'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='core.service', verbose_name='prescrição'),
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.AddField(
            model_name='evaluationattachment',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.evaluation', verbose_name='evolução'),
        ),
    ]
