# Generated by Django 3.2.13 on 2022-04-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220427_0956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluationattachment',
            options={'verbose_name': 'anexo de evolução', 'verbose_name_plural': 'anexos de evolução'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'unidade', 'verbose_name_plural': 'unidades'},
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(help_text='sobrenome', max_length=100, verbose_name='nome'),
        ),
    ]
